export const COVER_SAMPLES = [
  { name: "Professional", greeting: "Dear Hiring Manager,", opening: "I am writing to apply for the [Role] position at [Company]. My experience in [field] has prepared me to contribute from day one.", body: "At [Previous Company], I [specific achievement with measurable result]. I would bring the same attention to detail and collaborative approach to your team.", closing: "I would welcome the opportunity to discuss how my experience fits your goals. Thank you for your time and consideration." },
  { name: "Career change", greeting: "Dear Hiring Team,", opening: "I am excited to apply for the [Role] position. While my background is in [previous field], the skills I developed there translate directly to [new field].", body: "In my previous role, I [transferable accomplishment]. This taught me [relevant skill] and showed me how to deliver results in unfamiliar situations.", closing: "I would love to bring this perspective to [Company]. Thank you for considering my application." },
  { name: "Graduate", greeting: "Dear Hiring Manager,", opening: "I am applying for the [Role] position at [Company]. As a recent [degree] graduate, I am eager to put my training into practice.", body: "During [project or internship], I [contribution and result]. That experience strengthened my [relevant skill] and my enthusiasm for this work.", closing: "I would appreciate the chance to discuss how I could support your team. Thank you for considering my application." },
];

export const RESIGNATION_SAMPLES = [
  { name: "Standard notice", opening: "Please accept this letter as formal notice of my resignation from my position as [Role] at [Company]. My last working day will be [Date].", body: "I am grateful for the opportunities to learn and grow during my time here. I will do everything I can to ensure a smooth handover of my responsibilities.", closing: "Thank you for your support and understanding. I wish the team continued success." },
  { name: "Short and direct", opening: "I am writing to resign from my role as [Role] at [Company], effective [Date].", body: "I appreciate the experience I have gained here and will work with you to transition my current responsibilities before I leave.", closing: "Thank you for the opportunity to be part of the team." },
  { name: "Warm farewell", opening: "After careful consideration, I have decided to step down from my role as [Role]. My final day at [Company] will be [Date].", body: "Working with this team has been a meaningful chapter in my career. I especially appreciate [specific experience]. I am happy to help document my work and support the transition.", closing: "Thank you for your mentorship and trust. I hope we stay in touch." },
];